#!/usr/bin/env python3

# Compare with local file
# Diff with raw text from a file
# arg[1]: abs. filepath

import sys
from difflib import unified_diff
from pathlib import Path
from typing import Iterator

with open(sys.argv[1], 'r') as local:
    diff_iterator: Iterator[str] = unified_diff(sys.stdin.readlines(), local.readlines(),
                                                fromfile="<local_working_file>",
                                                tofile=str(Path(sys.argv[1]).absolute()))

    print(''.join(diff_iterator))
