#!/usr/bin/env python3

# Compare with remote file
# Diff with raw text from a URL
# arg[1]: rawtext URL

import sys
from difflib import unified_diff
from typing import Iterator

import requests

remote_url: str = sys.argv[1]

remote_file: requests.Response = requests.get(remote_url)
if remote_file.status_code != 200:
    sys.exit(remote_file.status_code)

# Redirect title
if len(remote_file.history) > 0:
    remote_url = remote_file.url + f" (redirected from {remote_url})"

diff_iterator: Iterator[str] = unified_diff(sys.stdin.readlines(),
                                            remote_file.text.splitlines(keepends=True),
                                            fromfile="<local_working_file>", tofile=remote_url)

print(''.join(diff_iterator))
