#!/usr/bin/env python3

# Compare with local file
# Diff with raw text from a file
# arg[1]: abs. filepath

from urllib import request, response
from typing import Iterator
import subprocess
import sys
from difflib import unified_diff

with open(sys.argv[1], 'r') as local:
    diff_iterator: Iterator[str] = unified_diff(sys.stdin.readlines(), local.readlines())

# Name the files
diff = list(diff_iterator)
diff[0] = diff[0][:-1] + "<local_working_file>" + diff[0][-1:]
diff[1] = diff[1][:-1] + sys.argv[1] + diff[1][-1:]

sys.stdout.writelines(diff)